.travis.yml
Travis does not support Open JDK 8 [1]. This updates to use Oracle JDK 8 for the build.
[1] https://docs.travis-ci.com/user/languages/java/#Overview
Reviewers
----
=> Use oraclejdk8 for Travis build

.travis.yml, README.md
Correct site URL in `README.md`.
Reviewers
----
=> Update documentation site url in README

.travis.yml, .travis/settings.xml, RELEASING.md, pom.xml
* Removed the unnecessary configuration for maven-release-plugin
* Update the release guide
* updated the travis configuration to also build tags.
----
n/a
Reviewers
----
=> Remove unnecessary release plugin configuration  

client/pom.xml
Downgraded the client modules to use Resteasy 3.0.12.Final so that it is compatible with Java 6. 3.0.13.Final+ require Java 7. Fixes #9.
----
Manually built (`mvn clean install`) the client modules using java 6.
How to test
----
Reviewers
----
=> Downgrade client dependency on Resteasy to 3.0.12.Final

CHANGELOG.md, CONTRIBUTORS.md, resteasy/src/main/java/com/cerner/beadledom/resteasy/ResteasyContextListener.java, resteasy/src/test/scala/com/cerner/beadledom/resteasy/BaseContextListenerSpec.scala
An infinite loop would occur in `ResteasyContextListener` if the Guice injector had a parent injector.
----
Added new unit test and verified that it resulted in an infinite loop before the fix was implemented.
How to test
----
Reviewers
----
=> Fix infinite loop in ResteasyContextListener when injector has parent

CONTRIBUTORS.md, README.md
I made these changes because there were discontiguous capitalization throughout the README. These changes are not necessary but they seemed more correct. I also am suggestion a few other changes where there was a long sentence or spacing at the end of a line.
----
There was no code change so I have not added any unit tests but I have run mvn clean install -U. https://gist.github.com/anelson425/31109213d045ed017106d49c27e94492
How to test
----
Reviewers
----
=> Readme updates for capitalization

CHANGELOG.md, client/beadledom-client-guice/src/main/java/com/cerner/beadledom/client/BeadledomClientBuilderProvider.java, client/beadledom-client-guice/src/main/java/com/cerner/beadledom/client/BeadledomClientPrivateModule.java, client/beadledom-client-guice/src/test/scala/com/cerner/beadledom/client/BeadledomClientModuleSpec.scala
`BeadledomClientBuilderProvider` was using a `Provider<Injector>` to get an instance of a Guice `Injector`. Since the provider defers getting an instance of an `Injector` until the provider is actually used, the context private module child Injectors is lost by the time an instance is retrieved. This provider should be using the nearest child injector from the private modules the client is being configured in. Changing the class to take an instance of `Injector` directly instead of a provider directly makes the injection more eager and results in the correct child injector being used.
----
Additional unit test.
How to test
----
Reviewers
----
=> Fixed BeadledomClientBuilderProvider using wrong injector

docs/source/manual/jaxrs_generic_response.rst
Corrected the generic response docs to show that `build` is required to get an instance of the `GenericRespone`.
----
n/a
How to test
----
Reviewers
----
=> Add chained build method to generic response docs

CHANGELOG.md, jaxrs-genericresponse/src/main/java/com/cerner/beadledom/jaxrs/DelegatingGenericResponse.java, jaxrs-genericresponse/src/main/java/com/cerner/beadledom/jaxrs/ResponseToStringWrapper.java, jaxrs-genericresponse/src/test/scala/com/cerner/beadledom/jaxrs/DelegatingGenericResponseSpec.scala, jaxrs-genericresponse/src/test/scala/com/cerner/beadledom/jaxrs/ResponseToStringWrapperSpec.scala, resteasy-genericresponse/src/main/java/com/cerner/beadledom/resteasy/BuiltGenericResponse.java, resteasy-genericresponse/src/test/scala/com/cerner/beadledom/resteasy/BuiltGenericResponseSpec.scala
Dumb but nice to have, added toString implementation to help testing and debugging. 
I originally did this while playing around with the client and implemented it on what the client sees (DelegatingGenericResponse) but I'm thinking this should instead be implemented on the interface (GenericResponse) instead otherwise you would likely want to implement toString on BuiltGenericResponse to be consistent. Let me know if you have a preference.
I also effectively implemented toString for raw Response otherwise you just get a reference to ApacheHttpClient4Dot3Engine on the client side and from what I can tell BuiltResponse on server side. I can't decide if I should try to provide a pull to resteasy to implement …
=> Added toString implementation to DelegatingGenericResponse

archetype/simple-service/src/main/resources/archetype-resources/pom.xml
Add the dependency version for guava and javax to the parent pom of the archetype
----
Generate a service through archetype and running it successfully
How to test
----
Reviewers
----
=> Fix dependency version issue in archetype

avro/jackson/src/main/java/com/cerner/beadledom/avro/AvroJacksonGuiceModule.java, avro/swagger/src/main/java/com/cerner/beadledom/avro/AvroSwaggerGuiceModule.java, client/beadledom-client-guice/src/main/java/com/cerner/beadledom/client/BeadledomClientProvider.java, client/beadledom-client/src/main/java/com/cerner/beadledom/client/BeadledomClientConfiguration.java, google_checks_1.8.xml, jaxrs-genericresponse/src/main/java/com/cerner/beadledom/jaxrs/GenericResponseBuilder.java, pom.xml
The checkstyle configuration within the pluginManagement section of the
pom was not being used when running the plugin. To get the configuration
to be used, the plugin configuration was removed from pluginManagement
and moved directly to the plugin within the build section.
The checkstyle jar version was also upgraded to 8.1. 8.2 is the latest
version, but it seems to have a bug where it blows up on escaped html
tags like `&lt;` or `&gt;` within javadoc.
----
Ran `mvn checkstyle:checkstyle` and `mvn clean install`
How to test
----
Reviewers
----
=> Fix checkstyle plugin to run again

CHANGELOG.md, configuration/src/main/java/com/cerner/beadledom/configuration/EnvironmentConfigurationSource.java, configuration/src/main/java/com/cerner/beadledom/configuration/XmlConfigurationSource.java, configuration/src/test/scala/com/cerner/beadledom/configuration/EnvironmentConfigurationSourceSpec.scala, docs/source/manual/configuration.rst
This PR adds a configuration sourced by environment variables. This will be beneficial when deploying a service using Docker.
----
Created a new project and added
```
install(ConfigurationSourcesModuleBuilder.newBuilder()
.addSource(EnvironmentConfigurationSource.create())
.build());
```
This allowed the reading of environment variables through the ImmutableHierarchicalConfiguration
How to test
----
Reviewers
----
=> Add environment variables configuration source

avro/jackson/pom.xml, client/beadledom-client-guice/pom.xml, client/beadledom-client-jackson/pom.xml, client/beadledom-client/pom.xml, client/beadledom-jaxrs-clientproxy/pom.xml, client/resteasy-client/pom.xml, common/pom.xml, configuration/pom.xml, google_checks_1.8.xml, health/api/pom.xml, health/service/pom.xml, health/service/src/test/scala/com/cerner/beadledom/health/resource/DependenciesResourceImplSpec.scala, health/service/src/test/scala/com/cerner/beadledom/health/resource/DiagnosticResourceImplSpec.scala, health/service/src/test/scala/com/cerner/beadledom/health/resource/HealthResourceImplSpec.scala, jackson/pom.xml, jaxrs-genericresponse/pom.xml, jaxrs/pom.xml, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/provider/CorrelationIdFilterBehaviors.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/provider/FilteringJacksonJsonProviderSpec.scala, lifecycle-governator/pom.xml, lifecycle/pom.xml, lifecycle/src/test/scala/com/cerner/beadledom/lifecycle/legacy/LifecycleProvisionListenerSpec.scala, pom.xml, resteasy-genericresponse/pom.xml, resteasy/pom.xml, stagemonitor/pom.xml, stagemonitor/src/test/scala/com/cerner/beadledom/stagemonitor/request/LogJsonRequestTraceReporterSpec.scala, swagger/pom.xml
Upgrades mockito from 1.x to 2.x.
----
* Ran existing tests.
* Ran `mvn dependency:tree | grep mockito` to confirm only 2.x versions were being pulled in.
How to test
----
Reviewers
----
=> Upgrade mockito to 2.10

CHANGELOG.md, archetype/simple-service/src/main/resources/archetype-resources/api/src/main/java/api/HelloWorldResource.java, archetype/simple-service/src/main/resources/archetype-resources/service/pom.xml, archetype/simple-service/src/main/resources/archetype-resources/service/src/main/java/service/ResteasyBootstrapModule.java, archetype/simple-service/src/main/resources/archetype-resources/service/src/main/java/service/__name__ContextListener.java, archetype/simple-service/src/main/resources/archetype-resources/service/src/main/java/service/resource/HelloWorldResourceImpl.java, core/pom.xml, core/src/main/java/com/cerner/beadledom/core/BeadledomModule.java, docs/source/index.rst, docs/source/manual/core.rst, docs/source/manual/resteasy.rst, docs/source/manual/swagger.rst, docs/source/releases/Beadledom30.rst, docs/source/releases/index.rst, resteasy/pom.xml, resteasy/src/main/java/com/cerner/beadledom/resteasy/ResteasyContextListener.java, resteasy/src/test/java/com/cerner/beadledom/resteasy/fauxservice/FauxModule.java
As outlined in #50 by @johnlcox we want the BeadledomModule to only install the minimal set of modules. This PR removes Avro, Swagger, and Stagemonitor from being installed from BeadledomModule.
----
* Made sure project still built.
* Generated a new project using the archetype and verified the generated code and service worked.
How to test
----
- Generate project and verify project functions correctly
Reviewers
----
=> Breaking up BeadledomModule 

CHANGELOG.md, client/pom.xml, client/resteasy-client/pom.xml, configuration/pom.xml, guice-dynamicbindings/pom.xml, guice/pom.xml, jackson/pom.xml, jaxrs-genericresponse/pom.xml, lifecycle/pom.xml, pom.xml, resteasy-genericresponse/pom.xml
Make Java 1.8 the minimum Java version so we no longer have a mismatch.
----
Existing unit tests and integration tests.
How to test
----
Reviewers
----
=> Upgrade modules to Java 1.8

resteasy/src/main/java/com/cerner/beadledom/resteasy/ResteasyModule.java
Resteasy 3.1+ no longer supports GZIP encoding by default. This adds back support for GZIP.
=> Add back support for GZIP encoding with the Resteasy 3.1 upgrade

dependency-check-suppressions.xml, pom.xml
Adds the `dependency-check-plugin` to scan dependencies for OWASP issues. Also updates the dependencies that have fixes and suppresses the ones that are false positives.
----
Ran `mvn clean install site`
How to test
----
Reviewers
----
=> Add dependency-check plugin

jaxrs-genericresponse/src/main/java/com/cerner/beadledom/jaxrs/GenericResponse.java
By extending the Closeable interface the GenericResponse interface will also
automatically extend the AutoClosable interface when used in a runtime
environment running Java 7+. This allows the response to be used with a
try-with-resources statement while still being Java 6 compatible.
----
Ran the existing tests.
How to test
----
Reviewers
----
=> Make GenericResponse extend the Closeable interface

CHANGELOG.md, client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/http/DefaultServiceUnavailableRetryStrategy.java, client/resteasy-client/src/test/scala/com/cerner/beadledom/client/resteasy/http/DefaultServiceUnavailableRetryStrategySpec.scala, client/resteasy-client/src/test/scala/com/cerner/beadledom/client/resteasy/http/X509HostnameVerifierAdapterSpec.scala
Fixes #44.
Change client retries to only retry 503 status codes.
----
Ran existing unit and integration tests.
How to test
----
=> Change the HttpClient  to only retry on 503 response codes

CHANGELOG.md, client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/BeadledomResteasyClientBuilder.java, docs/source/releases/Beadledom30.rst, pom.xml, resteasy/src/main/java/com/cerner/beadledom/resteasy/GzipContentEncodingFilter.java, resteasy/src/main/java/com/cerner/beadledom/resteasy/ResteasyModule.java
Upgrades to JAX-RS 2.1 and Resteasy 3.6.x
----
Existing tests and tried it with an existing beadledom service.
How to test
----
=> Jaxrs upgrade

CHANGELOG.md, client/beadledom-jaxrs-clientproxy/src/main/java/com/cerner/beadledom/client/proxy/GenericClientProxy.java, client/beadledom-jaxrs-clientproxy/src/test/java/com/cerner/beadledom/client/proxy/GenericTestingResource.java, client/beadledom-jaxrs-clientproxy/src/test/java/com/cerner/beadledom/client/proxy/StandardTestingResource.java, client/beadledom-jaxrs-clientproxy/src/test/scala/com/cerner/beadledom/client/proxy/GenericClientProxySpec.scala
Fixes #109 by handling jax-rs respones that do not have a entity.
Unit tested
=> Handle jax-rs responses that do not contain a entity (#109)

pom.xml
Added the `maven-pmd-plugin` to the parent pom with default rules per request in issue #78 
*Note* that this is set to _not_ fail the build at this time. 
Simply ran `./mvnw clean install -U` locally.
=> Added pmd plugin to parent pom. Resolves #78

CHANGELOG.md, dependency-check-suppressions.xml, swagger1/src/main/java/com/cerner/beadledom/swagger/SwaggerModule.java, swagger1/src/test/scala/com/cerner/beadledom/swagger/SwaggerModuleSpec.scala, swagger2/src/main/java/com/cerner/beadledom/swagger2/Swagger2Module.java, swagger2/src/test/scala/com/cerner/beadledom/swagger2/SwaggerModuleSpec.scala
Fixing a defect with swagger2 module where no default implementation of ModelConverter was bound.
Consumed SNAPSHOT version in another service
=> Swagger2 - Add empty multibinder for ModelConverter

CHANGELOG.md, pom.xml
The Travis CI build was failing because the log file is too long. One of the longest parts was caused by this 
which was found to be a defect in 3.1.6 spotbugs, and then subsequently fixed in 3.1.8. Hopefully this will be enough reduction in our logs to have travis pass.
I ran `mvn compile spotbugs:check` and made sure none of the previous spotbug errors occurred.
=> Uplift spotbug to 3.1.8 to eliminate incorrect bug identification

.travis/publish_site.sh, CHANGELOG.md
The Travis logs were once again too long. A major culprit of log length is progress updates when downloading external maven packages.
This change enables batch mode on the site generation (it was already enabled on the main mvn install). Batch mode will eliminate these progress updates from our log and hopefully will make it short enough.
The Progress updates themselves don't actually print to terminal when we are developing locally, but you can see them flash up on the bottom of the screen. Before the change I could see them briefly but after the change I couldn't see them at all. 
Also, the fact that when the `mvn install` command runs (with the batch option enabled) there are none of these progress updates in the output provided me with more confidence that I was making the right …
=> Fix site log length

.travis/publish_site.sh, CHANGELOG.md
The mvn site command was given the -q switch, which enables quiet mode. This will only let it output errors. This change was necessary because the site generation is what takes up the most of our logs, and this should help fix that issue. We will still print out errors, but prior to this change we were printing out `Forking ...` for each of our projects when we were building each of the projects for a total print out of 1,764 blocks that just tell us we are `Forking` other projects. 
I ran the site command with and without the flag to verify that the output was shorter.
=> Add quiet run to site generate command

CHANGELOG.md, pom.xml
Jackson databind has high severity security vulnerabilities as outlined here:
https://nvd.nist.gov/vuln/detail/CVE-2018-19360
https://nvd.nist.gov/vuln/detail/CVE-2018-19362
https://nvd.nist.gov/vuln/detail/CVE-2018-14720
https://nvd.nist.gov/vuln/detail/CVE-2018-19361
https://nvd.nist.gov/vuln/detail/CVE-2018-14719
https://nvd.nist.gov/vuln/detail/CVE-2018-14718
https://nvd.nist.gov/vuln/detail/CVE-2018-14721
this upgrades the version to a version without the vulnerabilities 
mvn clean install the project
=> Changing jackson version to 2.9.8 to fix vulnerability

CHANGELOG.md, pom.xml
Removes the exclusion of `jersey-media-multipart`. Turns out `swagger-jersey2-jaxrs` has an explicit dependency on this just for checking if it should be ignored: https://github.com/swagger-api/swagger-core/blob/v1.5.22/modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java#L71
Ran existing tests.
=> Remove jersey-media-multipart exclusion from swagger-jersey2-jaxrs

CHANGELOG.md, dependency-check-suppressions.xml, docs/source/manual/jooq.rst, jooq/src/main/java/com/cerner/beadledom/jooq/DSLContextProviderImpl.java, jooq/src/main/java/com/cerner/beadledom/jooq/JooqTransaction.java, jooq/src/main/java/com/cerner/beadledom/jooq/JooqTransactionalHooks.java, jooq/src/main/java/com/cerner/beadledom/jooq/ThreadLocalCommitHookExecutingTransactionListener.java, jooq/src/main/java/com/cerner/beadledom/jooq/ThreadLocalJooqModule.java, jooq/src/main/java/com/cerner/beadledom/jooq/ThreadLocalJooqTransactionalHooks.java, jooq/src/test/scala/com/cerner/beadledom/jooq/DSLContextProviderImplSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/JooqTransactionSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/ThreadLocalCommitHookExecutingTransactionListenerSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/ThreadLocalJooqModuleSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/ThreadLocalJooqTransactionalHooksSpec.scala, pom.xml
Adds a new transaction hooks class that can be used to register actions during a Jooq transaction to be executed after the transaction is successfully committed.
* New unit tests
* Used in a service and manually tested some transactions.
=> Add Jooq transaction hooks for executing actions on commit

CHANGELOG.md, client/beadledom-client-example/example-client/src/main/java/com/cerner/beadledom/client/example/client/ExampleOneClientModule.java, client/beadledom-client-guice/src/main/java/com/cerner/beadledom/client/BeadledomClientBuilderProvider.java, client/beadledom-client-guice/src/test/scala/com/cerner/beadledom/client/BeadledomClientModuleSpec.scala, client/beadledom-client-test/src/test/scala/com/cerner/beadledom/client/ClientServiceSpec.scala
> Addresses issue https://github.com/cerner/beadledom/issues/144
> White box test and integration test was updated
=> Guice-based Beadledom clients will now use the correct time unit for time outs

CHANGELOG.md, archetype/simple-service/src/main/resources/archetype-resources/pom.xml
Bumped the version of dependencies in the archetype to later versions that are not vulnerable to security vulnerabilities. I also ran into an issue when I used the archetype in 3.2.5 with `NoSuchMethodError` around guava (`java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)`) and after updating to a newer version (`java.lang.ClassNotFoundException: com.google.inject.multibindings.Multibinder`) since guice added multibinding extensions in a separate jar.
This also matches what beadledom libraries use
Create a sample project and updated the pom to get things working.
=> Update archetype to newer versions of dependencies

pom.xml
Jackson 2.9.9 had a security vulnerability.
mvn clean install
=> Upgrade jackson to 2.10

CHANGELOG.md, CONTRIBUTORS.md, jooq/src/main/java/com/cerner/beadledom/jooq/ThreadLocalCommitHookExecutingTransactionListener.java, jooq/src/test/scala/com/cerner/beadledom/jooq/ThreadLocalCommitHookExecutingTransactionListenerSpec.scala
If there is a exception while beginning the [transaction](https://github.com/jOOQ/jOOQ/blob/version-3.11.12/jOOQ/src/main/java/org/jooq/impl/DefaultDSLContext.java#L516) then TransactionListener#beginEnd
is never called. When this happened, ThreadLocalCommitHookExecutingTransactionListener#rollbackEnd would throw a NoSuchElementException since TransactionListener#beginEnd was never called setting up transactionDeques object
Updated existing tests.
=> Update ThreadLocalCommitHookExecutingTransactionListener to override TransactionListener#beginStart instead of TransactionListener#beginEnd

dependency-check-suppressions.xml, pom.xml
Add suppressions of swagger1 and stagemonitor since those will be removed with 4.0 release
=> Uplift to 5.2.2 of dependency-check-maven

jaxrs/src/main/java/com/cerner/beadledom/jaxrs/PATCH.java
Fixes #151. Deprecated custom PATCH annotation recommending to use annotation from JAX-RS 2.1, https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/PATCH.html
./mvnw clean install -U
=> Deprecate custom PATCH annotation, fixes #151

CHANGELOG.md, jooq/src/main/java/com/cerner/beadledom/jooq/DSLContextProviderImpl.java, pom.xml
* Nested transactions via `@JooqTransactional` no longer use SavePoints. Technically this a non-passive behavioral change, but seems like the safer option and likely what is more in line with what is expected by users of `@JooqTransactional`.
Tested by integrating it into Java service consuming Beadledom and confirmed performance boost as well as successful database commits
=> Defaulted to not use SavePoints for JooqTransactional module.

CHANGELOG.md, docs/source/manual/health.rst, health/service/pom.xml, health/service/src/main/java/com/cerner/beadledom/health/HttpHealthDependency.java, health/service/src/test/java/com/cerner/beadledom/health/HttpHealthDependencyTest.java, health/service/src/test/scala/com/cerner/beadledom/health/HealthModuleSpec.scala, pom.xml
* Adding HttpHealthDependency class to enable checking health of HTTP services.
* Tests
* Consumed it in a service locally.
=> Adding HttpHealthDependency helper class

CHANGELOG.md, health/api/src/main/java/com/cerner/beadledom/health/api/AvailabilityResource.java, health/api/src/main/java/com/cerner/beadledom/health/api/DependenciesResource.java, health/api/src/main/java/com/cerner/beadledom/health/api/DiagnosticResource.java, health/api/src/main/java/com/cerner/beadledom/health/api/HealthResource.java, health/api/src/main/java/com/cerner/beadledom/health/api/MediaType.java, health/api/src/main/java/com/cerner/beadledom/health/api/VersionResource.java, integration/service/pom.xml, pom.xml, resteasy/pom.xml, resteasy/src/test/resources/com/cerner/beadledom/resteasy/expected/api-docs-health.json, resteasy/src/test/resources/log4j.properties, resteasy/src/test/resources/logback.xml, resteasy/src/test/scala/com/cerner/beadledom/resteasy/ResteasyServiceSpec.scala
Adds [server relative quality factor](https://download.oracle.com/otn-pub/jcp/jaxrs-2_0_rev_A-mrel-eval-spec/jsr339-jaxrs-2.0-final-spec.pdf#section.3.5) to the health resources. Having this set removes the following message from being logged when calling a health endpoint without setting the `Accept` header.
```
WARN  o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002142: Multiple resource methods match request "GET /meta/health/". Selecting one. Matching methods: [public abstract javax.ws.rs.core.Response com.cerner.beadledom.health.api.HealthResource.getPrimaryHealthCheckHtml(), public abstract javax.ws.rs.core.Response com.cerner.beadledom.health.api.HealthResource.getPrimaryHealthCheck()]
```
=> Add server relative quality factor to health resources

CHANGELOG.md, avro/jackson/src/main/java/com/cerner/beadledom/avro/AvroMappingMixin.java, avro/pom.xml, docs/source/releases/Beadledom40.rst, docs/source/releases/index.rst, pom.xml, resteasy/pom.xml
Upgrades Avro to 1.10.0. There are CVE with Avro 1.7.5.
=> Upgrade Avro to 1.10.0

CHANGELOG.md, client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/ExponentialBackoffHttpRequestRetryHandler.java, client/resteasy-client/src/test/scala/com/cerner/beadledom/client/resteasy/ExponentialBackoffHttpRequestRetryHandlerSpec.scala
Starting with Java 1.8.0_272, SSLSocketImpl wraps SocketException - https://bugs.openjdk.java.net/browse/JDK-8214339. Beadledom Client is updated to retry on SSLExceptions that occur because of IOExceptions.
=> Update Beadledom Client to retry on SSLException when the cause is IOException

pom.xml
When upgrading jackson to mitigate CVE-2020-25649 in a consuming project, we needed to bump the swagger2 version because they are using a deprecated method.
Swagger core issue: https://github.com/swagger-api/swagger-core/issues/3554
Swagger core commit:  https://github.com/swagger-api/swagger-core/commit/0724ec80d214e97ddb8b8416f2b2cbad4651281c
Built locally.
=> Upgrade swagger2 and jackson versions
