cerner/beadledom

CHANGELOG.md
* Update CHANGELOG.md for 2.5 release.
----
N/A
How to test
----
Reviewers
----
=> Release Review 2.5

CHANGELOG.md
Preparing changelog for 2.5.1 release.
=> Prepare for 2.5.1 release

CHANGELOG.md
Preparing changelog for 2.6 release.
=> Prepare for 2.6 release

CHANGELOG.md
Preparing changelog for 2.6.1 release.
=> Prepare for 2.6.1 release

CHANGELOG.md, checkstyle-suppressions.xml, docs/source/manual/index.rst, docs/source/manual/jooq.rst, jooq/pom.xml, jooq/src/main/java/com/cerner/beadledom/jooq/DSLContextProvider.java, jooq/src/main/java/com/cerner/beadledom/jooq/DSLContextProviderImpl.java, jooq/src/main/java/com/cerner/beadledom/jooq/JooqTransactional.java, jooq/src/main/java/com/cerner/beadledom/jooq/JooqTxnInterceptor.java, jooq/src/main/java/com/cerner/beadledom/jooq/ThreadLocalJooqModule.java, jooq/src/main/java/com/cerner/beadledom/jooq/UnitOfWork.java, jooq/src/test/scala/com/cerner/beadledom/jooq/DSLContextProviderImplSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/EmptyMockDataProvider.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/JooqTxnInterceptorSpec.scala, jooq/src/test/scala/com/cerner/beadledom/jooq/ThreadLocalJooqModuleSpec.scala, pom.xml
Adds a new module for using jOOQ for database interactions.
----
unit tests
How to test
----
Reviewers
----
=> Add jooq module with ThreadLocal Guice module

bom/pom.xml
*Explain the changes included in this request, and the reasons for them.*
----
*Describe the strategy you used to validate these changes. For example, this should mention if you added unit/integration tests and summarize any manual testing you performed by running your branch locally or in a dev environment.*
How to test
----
Reviewers
----
=> Add beadledom-jooq to bom

bom/pom.xml
*Explain the changes included in this request, and the reasons for them.*
Added `beadledom-json-common` to the BOM to allow it's import with the BOM.
----
*Describe the strategy you used to validate these changes. For example, this should mention if you added unit/integration tests and summarize any manual testing you performed by running your branch locally or in a dev environment.*
No functional changes. `mvn clean -U install site` succeeded.
----
Reviewers
----
=> Issue #82: Added beadledom-json-common to beadledom-bom (2.x)

health/service/src/main/java/com/cerner/beadledom/health/internal/HealthChecker.java
Fix `HealthChecker` to actually log dependency exceptions. Previously it was passing the `Optional` to the logger rather than the actual exception.
----
Existing unit/integration tests.
How to test
----
=> Fix HealthChecker to log dependency exceptions

health/api/src/main/java/com/cerner/beadledom/health/dto/BuildDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/HealthDependenciesDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/HealthDependencyDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/HealthDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/HttpServiceDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/LinksDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/ServerDto.java, health/api/src/main/java/com/cerner/beadledom/health/dto/TypeDto.java, health/api/src/test/scala/com/cerner/beadledom/health/dto/BuildDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/HealthDependenciesDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/HealthDependencyDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/HealthDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/HttpServiceDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/JacksonSerializationBehaviors.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/LinksDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/ServerDtoSpec.scala, health/api/src/test/scala/com/cerner/beadledom/health/dto/TypeDtoSpec.scala
* Fixes health DTOs Jackson deserialization by adding @JsonDeserialize and @JsonCreator
----
* Unit test
How to test
----
=> Fix health DTOs Jackson deserialization

CHANGELOG.md
Update CHANGELOG for issue 67
----
*Describe the strategy you used to validate these changes. For example, this should mention if you added unit/integration tests and summarize any manual testing you performed by running your branch locally or in a dev environment.*
How to test
----
=> Issue 67 CHANGELOG update

pom.xml
Upgrade plugins to latest versions
----
Ran `mvn clean install`
How to test
----
=> Upgrade plugins to latest versions

client/beadledom-client/pom.xml, common/pom.xml, configuration/src/test/scala/com/cerner/beadledom/configuration/BeadledomConfigurationModuleSpec.scala, health/api/pom.xml, health/service/pom.xml, jackson/pom.xml, json-common/pom.xml, lifecycle/src/test/scala/com/cerner/beadledom/lifecycle/legacy/BeadledomLifecycleModuleSpec.scala, pom.xml
Updated dependency versions.
----
Ran existing tests and included in a service and ran the services tests.
How to test
----
=> Update dependency versions

CHANGELOG.md, docs/source/guides/troubleshooting.rst, docs/source/releases/Beadledom30.rst
Update docs for 3.0 release
Generated site and verified links worked.
=> Prepare for 3.0 release

client/beadledom-client-example/example-api/src/main/java/com/cerner/beadledom/client/example/model/JsonOne.java, client/beadledom-client-example/example-api/src/main/java/com/cerner/beadledom/client/example/model/JsonTwo.java, client/beadledom-client-jackson/pom.xml, client/beadledom-client-jackson/src/main/java/com/cerner/beadledom/client/jackson/AnnotatedJacksonModule.java, common/src/main/java/com/cerner/beadledom/metadata/BuildInfo.java
Fixes maven-javadoc-plugin errors
=> Fixes maven-javadoc-plugin errors

pom.xml
=> Fixes plugin configuration for javadoc and maven-project-info-reports-plugin plugins

archetype/simple-service/src/main/resources/archetype-resources/service/local/META-INF/context.xml, client/beadledom-client-example/example-service/src/main/resources/com/cerner/beadledom/client/context.xml, client/resteasy-client/src/test/resources/com/cerner/beadledom/client/context.xml, pom.xml, resteasy/src/test/resources/com/cerner/beadledom/resteasy/fauxservice/context.xml
Uplift to Tomcat 7.0.91
`./mvnw clean install -U`
=> Uplift to Tomcat 7.0.91

CHANGELOG.md, pagination/src/main/java/com/cerner/beadledom/pagination/OffsetPaginatedList.java, pagination/src/test/scala/com/cerner/beadledom/pagination/OffsetPaginatedListSpec.scala, pagination/src/test/scala/com/cerner/beadledom/pagination/OffsetPaginationLinksSpec.scala
=> Deprecate pagination list metadata convenience overloads

CHANGELOG.md
=> Update Changelog to show released 3.3

client/beadledom-client-jackson/src/main/java/com/cerner/beadledom/client/jackson/ObjectMapperClientFeatureModule.java, configuration/src/main/java/com/cerner/beadledom/configuration/XmlConfigurationSource.java, health/service/src/main/java/com/cerner/beadledom/health/HealthModule.java, jackson/src/main/java/com/cerner/beadledom/jackson/JacksonModule.java, jaxrs/src/main/java/com/cerner/beadledom/jaxrs/JaxRsModule.java, pagination/src/main/java/com/cerner/beadledom/pagination/OffsetPaginationLinks.java, pom.xml, swagger1/src/main/java/com/cerner/beadledom/swagger/SwaggerUiResource.java
Fixed PMD violations and set plugin to fail on violations
Travis build: https://travis-ci.com/sairamvudatha/beadledom/jobs/241797947
=> Fix PMD violations, fixes #122

CHANGELOG.md, dependency-check-suppressions.xml, pom.xml
=> Update CHANGELOG.md for issue #151

CHANGELOG.md
=> Update CHANGELOG.md for 3.5 release

docs/source/releases/Beadledom40.rst
=> Add 4.0 migration guide

CHANGELOG.md, client/pom.xml, client/resteasy-client/pom.xml, client/resteasy-client/src/test/java/com/cerner/beadledom/client/FauxModule.java, jaxrs/src/main/java/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapper.java, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/JsonMappingExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/JsonParseExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/ThrowableExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapperSpec.scala, pom.xml, resteasy/src/test/scala/com/cerner/beadledom/resteasy/exceptionmapping/FailureExceptionMapperSpec.scala
=> Resteasy 3.11 uplift

CHANGELOG.md, client/beadledom-client-test/pom.xml, client/pom.xml, client/resteasy-client/pom.xml, client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/BeadledomResteasyClientBuilder.java, client/resteasy-client/src/main/java/com/cerner/beadledom/client/resteasy/ResteasyCorrelationIdContext.java, client/resteasy-client/src/test/java/com/cerner/beadledom/client/FauxModule.java, client/resteasy-client/src/test/scala/com/cerner/beadledom/client/resteasy/ResteasyClientSpec.scala, health/service/pom.xml, health/service/src/test/scala/com/cerner/beadledom/health/internal/HealthCheckerSpec.scala, integration/pom.xml, jaxrs/pom.xml, jaxrs/src/main/java/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapper.java, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/PATCHSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/JsonMappingExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/JsonParseExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/ThrowableExceptionMapperSpec.scala, jaxrs/src/test/scala/com/cerner/beadledom/jaxrs/exceptionmapping/WebApplicationExceptionMapperSpec.scala, pagination/pom.xml, pagination/src/test/scala/com/cerner/beadledom/pagination/OffsetPaginatedListLinksWriterInterceptorSpec.scala, pagination/src/test/scala/com/cerner/beadledom/pagination/OffsetPaginationLinksSpec.scala, pagination/src/test/scala/com/cerner/beadledom/pagination/parameters/OffsetPaginationParametersSpec.scala, pom.xml, resteasy-genericresponse/pom.xml, resteasy/pom.xml, resteasy/src/main/java/com/cerner/beadledom/resteasy/GzipContentEncodingFilter.java, resteasy/src/main/java/com/cerner/beadledom/resteasy/ResteasyModule.java, resteasy/src/test/scala/com/cerner/beadledom/resteasy/InjectorProcessorSpec.scala, resteasy/src/test/scala/com/cerner/beadledom/resteasy/ResteasyServiceSpec.scala, resteasy/src/test/scala/com/cerner/beadledom/resteasy/exceptionmapping/FailureExceptionMapperSpec.scala
* Uplift to resteasy-4
* Tested with a service locally
* Unit and integration tests.
=> Resteasy4 uplift

docs/source/manual/pagination.rst
> Fixed link to OffsetPaginatedList.java
> It wasn't. Just a small doc change :)
=> Fixed link to OffsetPaginatedList.java

CHANGELOG.md
=> Update changelog for 3.6 release

CHANGELOG.md
=> Update changelog for 4.1 release
